[package]
name = "rcompress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rcompress"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
itertools = "0.11.0"
