[package]
name = "rjson"
version = "0.0.1"
description = "Sample json parser for coding challenges"
edition = "2021"

[lib]
name = "rjson"
path = "src/lib.rs"

[dependencies]
regex = "1.9.3"
thiserror = "1.0.44"

[dev-dependencies]
rstest = "0.18.2"